"""Scoped pairing copy, added without rewriting existing messages."""
KEYS = (
    "pairingTitle", "pairingScanQr", "pairingImageQr", "pairingLink",
    "pairingConfirm", "pairingRejected", "pairingUncertain", "pairingCaptureError",
    "pairingRenew", "pairingAgain", "pairingExpires", "pairingPaired",
)
COPY = {
    "en": ("Pair a server", "Scan QR", "Open QR image", "Pairing link", "Confirm and pair", "This link is invalid, expired or already used. Generate a new link.", "The pairing outcome is unknown. Generate a new link; this request will not be repeated.", "Could not read this QR. Use a PNG/JPEG image or paste the link.", "Renew token", "Pair again", "Declared token expiry", "Paired"),
    "pt": ("Parear servidor", "Ler QR", "Abrir imagem QR", "Link de pareamento", "Confirmar e parear", "Este link é inválido, expirou ou já foi usado. Gere outro link.", "O resultado do pareamento é desconhecido. Gere outro link; esta solicitação não será repetida.", "Não foi possível ler o QR. Use uma imagem PNG/JPEG ou cole o link.", "Renovar token", "Parear novamente", "Validade declarada do token", "Pareado"),
    "es": ("Emparejar servidor", "Escanear QR", "Abrir imagen QR", "Enlace de emparejamiento", "Confirmar y emparejar", "El enlace no es válido, caducó o ya se usó. Genera otro.", "El resultado es desconocido. Genera otro enlace; la solicitud no se repetirá.", "No se pudo leer el QR. Usa PNG/JPEG o pega el enlace.", "Renovar token", "Emparejar de nuevo", "Caducidad declarada del token", "Emparejado"),
    "fr": ("Appairer un serveur", "Scanner le QR", "Ouvrir une image QR", "Lien d’appairage", "Confirmer et appairer", "Lien invalide, expiré ou déjà utilisé. Générez un nouveau lien.", "Résultat inconnu. Générez un nouveau lien ; la requête ne sera pas répétée.", "QR illisible. Utilisez PNG/JPEG ou collez le lien.", "Renouveler le jeton", "Appairer à nouveau", "Expiration déclarée du jeton", "Appairé"),
    "de": ("Server koppeln", "QR scannen", "QR-Bild öffnen", "Kopplungslink", "Bestätigen und koppeln", "Link ungültig, abgelaufen oder verwendet. Neuen Link erstellen.", "Ergebnis unbekannt. Neuen Link erstellen; die Anfrage wird nicht wiederholt.", "QR nicht lesbar. PNG/JPEG verwenden oder Link einfügen.", "Token erneuern", "Erneut koppeln", "Angegebenes Token-Ablaufdatum", "Gekoppelt"),
    "it": ("Associa server", "Scansiona QR", "Apri immagine QR", "Link di associazione", "Conferma e associa", "Link non valido, scaduto o già usato. Generane un altro.", "Esito sconosciuto. Genera un altro link; la richiesta non sarà ripetuta.", "QR illeggibile. Usa PNG/JPEG o incolla il link.", "Rinnova token", "Associa di nuovo", "Scadenza dichiarata del token", "Associato"),
    "ru": ("Подключить сервер", "Сканировать QR", "Открыть изображение QR", "Ссылка подключения", "Подтвердить подключение", "Ссылка недействительна, истекла или использована. Создайте новую.", "Результат неизвестен. Создайте новую ссылку; запрос не повторяется.", "QR не распознан. Используйте PNG/JPEG или вставьте ссылку.", "Обновить токен", "Подключить снова", "Заявленный срок токена", "Подключено"),
    "ar": ("إقران خادم", "مسح QR", "فتح صورة QR", "رابط الإقران", "تأكيد الإقران", "الرابط غير صالح أو منتهي أو مستخدم. أنشئ رابطًا جديدًا.", "نتيجة الإقران غير معروفة. أنشئ رابطًا جديدًا؛ لن يُكرر الطلب.", "تعذرت قراءة QR. استخدم PNG/JPEG أو الصق الرابط.", "تجديد الرمز", "الإقران مجددًا", "انتهاء الرمز المعلن", "مقترن"),
    "ur": ("سرور جوڑیں", "QR اسکین کریں", "QR تصویر کھولیں", "جوڑنے کا لنک", "تصدیق کرکے جوڑیں", "لنک غلط، ختم شدہ یا استعمال شدہ ہے۔ نیا لنک بنائیں۔", "نتیجہ نامعلوم ہے۔ نیا لنک بنائیں؛ درخواست دہرائی نہیں جائے گی۔", "QR پڑھا نہیں جا سکا۔ PNG/JPEG استعمال کریں یا لنک چسپاں کریں۔", "ٹوکن کی تجدید", "دوبارہ جوڑیں", "ٹوکن کی بیان کردہ میعاد", "جڑا ہوا"),
    "hi": ("सर्वर जोड़ें", "QR स्कैन करें", "QR चित्र खोलें", "जोड़ने का लिंक", "पुष्टि करके जोड़ें", "लिंक अमान्य, समाप्त या इस्तेमाल हो चुका है। नया लिंक बनाएँ।", "परिणाम अज्ञात है। नया लिंक बनाएँ; अनुरोध दोहराया नहीं जाएगा।", "QR पढ़ नहीं सके। PNG/JPEG या लिंक का उपयोग करें।", "टोकन नवीनीकरण", "फिर से जोड़ें", "टोकन की घोषित समाप्ति", "जुड़ा हुआ"),
    "bn": ("সার্ভার জোড়া দিন", "QR স্ক্যান করুন", "QR ছবি খুলুন", "জোড়া দেওয়ার লিংক", "নিশ্চিত করে জোড়া দিন", "লিংক অবৈধ, মেয়াদোত্তীর্ণ বা ব্যবহৃত। নতুন লিংক তৈরি করুন।", "ফলাফল অজানা। নতুন লিংক তৈরি করুন; অনুরোধ পুনরাবৃত্তি হবে না।", "QR পড়া যায়নি। PNG/JPEG ব্যবহার করুন বা লিংক পেস্ট করুন।", "টোকেন নবায়ন", "আবার জোড়া দিন", "টোকেনের ঘোষিত মেয়াদ", "জোড়া দেওয়া"),
    "ja": ("サーバーをペアリング", "QRをスキャン", "QR画像を開く", "ペアリングリンク", "確認してペアリング", "リンクが無効、期限切れ、または使用済みです。新しいリンクを作成してください。", "結果が不明です。新しいリンクを作成してください。要求は再送されません。", "QRを読み取れません。PNG/JPEG画像またはリンクを使用してください。", "トークンを更新", "再ペアリング", "トークンの申告有効期限", "ペアリング済み"),
    "ko": ("서버 페어링", "QR 스캔", "QR 이미지 열기", "페어링 링크", "확인 후 페어링", "링크가 잘못되었거나 만료 또는 사용되었습니다. 새 링크를 만드세요.", "결과를 알 수 없습니다. 새 링크를 만드세요. 요청은 재전송되지 않습니다.", "QR을 읽지 못했습니다. PNG/JPEG 또는 링크를 사용하세요.", "토큰 갱신", "다시 페어링", "토큰의 명시된 만료", "페어링됨"),
    "zh": ("配对服务器", "扫描二维码", "打开二维码图片", "配对链接", "确认并配对", "链接无效、已过期或已使用。请生成新链接。", "配对结果未知。请生成新链接；不会重复此请求。", "无法读取二维码。请使用PNG/JPEG图片或粘贴链接。", "续期令牌", "重新配对", "令牌声明的到期时间", "已配对"),
}
