// GENERATED CODE - DO NOT MODIFY BY HAND.
// Offline selective port: tool/theme/port_v2_appearance.py

enum OpenCodeThemePreset {
  oc2,
  amoled,
  aura,
  ayu,
  carbonfox,
  catppuccin,
  catppuccinFrappe,
  catppuccinMacchiato,
  cobalt2,
  cursor,
  dracula,
  tokyonight,
  everforest,
  flexoki,
  github,
  gruvbox,
  kanagawa,
  lucentOrng,
  material,
  mercury,
  monokai,
  nightowl,
  nord,
  onedarkPro,
  opencode,
  orng,
  osakaJade,
  palenight,
  rosepine,
  shadesofpurple,
  solarized,
  synthwave84,
  vercel,
  vesper,
  zenburn,
  matrix,
  oneDark,
}

String openCodeThemePresetKey(OpenCodeThemePreset preset) {
  return switch (preset) {
    OpenCodeThemePreset.oc2 => 'oc-2',
    OpenCodeThemePreset.amoled => 'amoled',
    OpenCodeThemePreset.aura => 'aura',
    OpenCodeThemePreset.ayu => 'ayu',
    OpenCodeThemePreset.carbonfox => 'carbonfox',
    OpenCodeThemePreset.catppuccin => 'catppuccin',
    OpenCodeThemePreset.catppuccinFrappe => 'catppuccin-frappe',
    OpenCodeThemePreset.catppuccinMacchiato => 'catppuccin-macchiato',
    OpenCodeThemePreset.cobalt2 => 'cobalt2',
    OpenCodeThemePreset.cursor => 'cursor',
    OpenCodeThemePreset.dracula => 'dracula',
    OpenCodeThemePreset.tokyonight => 'tokyonight',
    OpenCodeThemePreset.everforest => 'everforest',
    OpenCodeThemePreset.flexoki => 'flexoki',
    OpenCodeThemePreset.github => 'github',
    OpenCodeThemePreset.gruvbox => 'gruvbox',
    OpenCodeThemePreset.kanagawa => 'kanagawa',
    OpenCodeThemePreset.lucentOrng => 'lucent-orng',
    OpenCodeThemePreset.material => 'material',
    OpenCodeThemePreset.mercury => 'mercury',
    OpenCodeThemePreset.monokai => 'monokai',
    OpenCodeThemePreset.nightowl => 'nightowl',
    OpenCodeThemePreset.nord => 'nord',
    OpenCodeThemePreset.onedarkPro => 'onedarkpro',
    OpenCodeThemePreset.opencode => 'opencode',
    OpenCodeThemePreset.orng => 'orng',
    OpenCodeThemePreset.osakaJade => 'osaka-jade',
    OpenCodeThemePreset.palenight => 'palenight',
    OpenCodeThemePreset.rosepine => 'rosepine',
    OpenCodeThemePreset.shadesofpurple => 'shadesofpurple',
    OpenCodeThemePreset.solarized => 'solarized',
    OpenCodeThemePreset.synthwave84 => 'synthwave84',
    OpenCodeThemePreset.vercel => 'vercel',
    OpenCodeThemePreset.vesper => 'vesper',
    OpenCodeThemePreset.zenburn => 'zenburn',
    OpenCodeThemePreset.matrix => 'matrix',
    OpenCodeThemePreset.oneDark => 'one-dark',
  };
}

OpenCodeThemePreset? openCodeThemePresetFromKey(String value) {
  return switch (value) {
    'system' => OpenCodeThemePreset.oc2,
    'oc-1' => OpenCodeThemePreset.oc2,
    'oc-2' => OpenCodeThemePreset.oc2,
    'amoled' => OpenCodeThemePreset.amoled,
    'aura' => OpenCodeThemePreset.aura,
    'ayu' => OpenCodeThemePreset.ayu,
    'carbonfox' => OpenCodeThemePreset.carbonfox,
    'catppuccin' => OpenCodeThemePreset.catppuccin,
    'catppuccin-frappe' => OpenCodeThemePreset.catppuccinFrappe,
    'catppuccin-macchiato' => OpenCodeThemePreset.catppuccinMacchiato,
    'cobalt2' => OpenCodeThemePreset.cobalt2,
    'cursor' => OpenCodeThemePreset.cursor,
    'dracula' => OpenCodeThemePreset.dracula,
    'tokyonight' => OpenCodeThemePreset.tokyonight,
    'everforest' => OpenCodeThemePreset.everforest,
    'flexoki' => OpenCodeThemePreset.flexoki,
    'github' => OpenCodeThemePreset.github,
    'gruvbox' => OpenCodeThemePreset.gruvbox,
    'kanagawa' => OpenCodeThemePreset.kanagawa,
    'lucent-orng' => OpenCodeThemePreset.lucentOrng,
    'material' => OpenCodeThemePreset.material,
    'mercury' => OpenCodeThemePreset.mercury,
    'monokai' => OpenCodeThemePreset.monokai,
    'nightowl' => OpenCodeThemePreset.nightowl,
    'nord' => OpenCodeThemePreset.nord,
    'onedarkpro' => OpenCodeThemePreset.onedarkPro,
    'opencode' => OpenCodeThemePreset.opencode,
    'orng' => OpenCodeThemePreset.orng,
    'osaka-jade' => OpenCodeThemePreset.osakaJade,
    'palenight' => OpenCodeThemePreset.palenight,
    'rosepine' => OpenCodeThemePreset.rosepine,
    'shadesofpurple' => OpenCodeThemePreset.shadesofpurple,
    'solarized' => OpenCodeThemePreset.solarized,
    'synthwave84' => OpenCodeThemePreset.synthwave84,
    'vercel' => OpenCodeThemePreset.vercel,
    'vesper' => OpenCodeThemePreset.vesper,
    'zenburn' => OpenCodeThemePreset.zenburn,
    'matrix' => OpenCodeThemePreset.matrix,
    'one-dark' => OpenCodeThemePreset.oneDark,
    _ => null,
  };
}
